### PR TITLE
Maintain eco-bot; switch to discord.py; beg command and overall improvements

### PR DESCRIPTION
**Pull request by infinotiver**
Hello @AyushSehrawat, as mentioned in #32 
here is my initial pr which revamps the fundamentals of eco-bot
## Here is a list of what changed
* `py-cord` --> `discord.py` : Discord.py is a lot convenient and popularly used and maintained regularly now
* migrate to `discord.py` :  Certain methods were outdated, for eg. `avatar_url`; `icon_url` etc
* Update in error handling : I removed try and except and instead added error handling in the `Errors` cog
* Beg command : For poor folks to earn some currency
* Bot Info Command : Updated your username and added mine
* Remove `discord-pretty-help` : `help-command` no longer works as desired

If you want, I can fully migrate this bot to support slash commands (but that would require some intense labour which I am unwilling to do )

:)

### CODE REVIEW

**Comment by infinotiver** [comment]
Also correct  a small typo
`on_connnect` to `on_connect`
(extra n removed )

**Comment by infinotiver** [comment]
# Screenshots
for @AyushSehrawat specifically (just for quick future reference)

image
image
image
Rest all commands are left unchanged except for changes in `discord.py` method and work as desired

**Comment by infinotiver** [comment]
> Also if possible, can you put fixed versions in requirements.txt, like `discord.py == x.x.x` (checkout [this](https://pip.pypa.io/en/stable/reference/requirements-file-format/) for more )
> 
> Or switch to poetry and generate a requirements.txt
> 
> The PR looks good, once the above suggestions have been applied i will merged it :)


@AyushSehrawat it is not necessary to have strict fixed versions. I usually don't prefer them but in this case, I am also not prefering them because there are some major changes in Discord and how discord apps work and there will be huge developments and changes in the `discord.py` library in coming days, so it is not practical to have fixed versions to ensure compatibility.

**Comment by infinotiver** [comment]
> The PR looks good, once the above suggestions have been applied i will merged it :)

Please merge it in its present state only.

**Comment by AyushSehrawat** [comment]
> > Also if possible, can you put fixed versions in requirements.txt, like `discord.py == x.x.x` (checkout [this](https://pip.pypa.io/en/stable/reference/requirements-file-format/) for more )
> > Or switch to poetry and generate a requirements.txt
> > The PR looks good, once the above suggestions have been applied i will merged it :)
> 
> @AyushSehrawat it is not necessary to have strict fixed versions. I usually don't prefer them but in this case, I am also not prefering them because there are some major changes in Discord and how discord apps work and there will be huge developments and changes in the `discord.py` library in coming days, so it is not practical to have fixed versions to ensure compatibility.

The same applies to code, if latest version has some breaking changes the current code will break

**Comment by infinotiver** [comment]
@AyushSehrawat  Added fixed versions

**Pull request merged**
