### PR TITLE
Completely migrate to python-dotenv, to support environment variables for enhanced security

### PR DESCRIPTION
**Pull request by infinotiver**
Do you need a description for this too?

Just updated all cogs and main.py to use dotenv instead of data.json, also updated the README to include new install and usage guide

### CODE REVIEW

**Comment by AyushSehrawat** [comment]
Create a `.env.example` too which can easily be renamed to `.env`

Also merge this pr with #34 since the changes are different. I don't know what's the point of two pull requests

**Comment by infinotiver** [comment]
> Create a `.env.example` too which can easily be renamed to `.env`
Added,
as for the latter request, I already told you why it can't be done

**Comment by AyushSehrawat** [comment]
> > Create a `.env.example` too which can easily be renamed to `.env`
> 
> Added, as for the latter request, I already told you why it can't be done

Just git merge/rebase, not a big deal

**Comment by infinotiver** [comment]
> Just git merge/rebase, not a big deal

Let it be separate, to avoid confusion and let's keep it organised

**Comment by infinotiver** [comment]
@AyushSehrawat merge this also, dotenv is highly required.....

**Review by AyushSehrawat — APPROVED** [review]

**Pull request merged**
